#!/usr/bin/env bash

# Aliases
alias aliases="alias | sed 's/=.*//'"

## Bash/ZSH specific

# Git
alias cdgr='cd "$(git root)"' # cd to git root directory

for method in commit clone checkout merge pull push fetch; do
	alias "${method}"="git '${method}'"
done

alias brewfile="source ~/dotfiles/brew/brew.sh"
alias npmfile='npm install -g $(cat ~/dotfiles/node/npmfile)'

alias myip="curl http://ipecho.net/plain; echo"
alias locip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"
alias captive="curl -s 'http://captive.apple.com'"

# Java
alias java_versions="/usr/libexec/java_home -V "
# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"
alias pi='ssh pi@raspberrypi.local'

## Apps (these work without alias: github, sourcetree, atom, hyper)
for method in arduino barrier bettertouchtool notes slack sketch safari terminal trello whatsapp xcode; do
	alias "${method}"="open -a '${method}'"
done
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

## Media
alias youtube='cd ~/Desktop; $(command -v youtube-dl)'
alias yv='googler -w youtube.com --url-handler open-pip $argv' # search for a youtube video & open it in PiP
alias youtube-mp3='$(command -v youtube-dl) -x --audio-format mp3'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

alias quicklook="qlmanage -p &>/dev/null" # quicklook from command line

alias killmenubar="killall SystemUIServer NotificationCenter"
alias killos="killfinder && killdock && killmenubar"

## Shell

# Enable aliases to be sudo’ed
alias sudo='sudo '
# Reload the shell (i.e. invoke as a login shell)
alias reload='exec ${SHELL} -l'

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# copy the working directory path
alias cpwd='pwd|tr -d "\n"|pbcopy'
alias lastMark='cd lastMark'

## ls
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
  # shellcheck disable=SC2034
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# List all files colorized in long format
alias l='ls -lF ${colorflag}'

# List all files colorized in long format, excluding . and ..
alias la='ls -lAF ${colorflag}'

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
alias ls='command ls ${colorflag}'

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge="tput bel"

# info
alias displays="system_profiler SPDisplaysDataType"
alias cpuinfo="sysctl -n machdep.cpu.brand_string"
alias cpu='top -o cpu'   # CPU
alias mem='top -o rsize' # Memory
# Disk
alias df='df -h'
alias du='du -h'

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# JavaScriptCore REPL
jscbin="/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc";
[ -e "${jscbin}" ] && alias jsc="${jscbin}";
unset jscbin;

# Trim new lines and copy to clipboard
#alias c="tr -d '\n' | pbcopy"

# Recursively delete `.DS_Store` files
alias cleanup-ds="find . -type f -name '*.DS_Store' -ls -delete"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Airport CLI alias
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Make Grunt print stack traces by default
command -v grunt > /dev/null && alias grunt="grunt --stack"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Convenience
alias nf="npmfile"
alias pf="pipfile"
alias ql="quicklook"
alias c="clear"
alias x="exit"
alias e="x"
alias quit="exit"
alias any="anybash"
alias newfile="newscript"
alias zm="zoom join "

## lol (only in bash)
if [ -n "$BASH_VERSION" ]; then
  alias please="sudo"

  # http://xkcd.com/530/
  alias stfu="osascript -e 'set volume output muted true'"
  alias pumpitup="osascript -e 'set volume output volume 100'"

  alias shrug="printf '¯\_(ツ)_/¯' | pbcopy"
  alias tableflip="printf '(╯°□°)╯︵ ┻━┻' | pbcopy"
  alias tf="printf '(╯°□°)╯︵ ┻━┻' | pbcopy"
  alias fight="printf '(ง'̀-'́)ง' | pbcopy"

  # alias wtf='hint'
  alias rtfm='man'

  alias visible='echo'
  alias invisible='cat'
  alias moar='more'

  alias icanhas='mkdir'
  alias donotwant='rm'
  alias dowant='cp'
  alias gtfo='mv'

  alias hai='cd'
  alias plz='pwd'

  alias inur='locate'

  alias nomz='ps -aux'
  alias nomnom='killall'

  alias cya='reboot'
  alias kthxbai='halt'
  # https://github.com/busyloop/lolcat
  alias cowcat='fortune | cowsay | lolcat'
  alias devcow='devquote | cowsay | lolcat'
  # https://gist.github.com/graceavery/01ec404e555571a4a668c271c8f62e8b
  alias accio=wget
  alias avadaKedavra='rm -f'
  alias imperio=sudo
  alias priorIncantato='echo `history |tail -n2 |head -n1` | sed "s/[0-9]* //"'
  alias stupefy='sleep 5'
  alias lumos="osascript -e 'tell app \"System Events\" to tell appearance preferences to set dark mode to false'"
  alias nox="osascript -e 'tell app \"System Events\" to tell appearance preferences to set dark mode to true'"
  alias wingardiumLeviosa=mv
  alias sonorus='set -v'
  alias quietus='set +v'
  alias colloportus='openssl enc -aes-256-cbc'  # locking spell!  $colloportus -in unencryptedName -out encryptedName
  alias alohamora='openssl enc -d -aes-256-cbc'  # unlocking spell!  $alohamora -in encryptedName -out unencryptedName
  alias reducio='zip -r'  # $reducio zippedName thingToZip
  alias engorgio=unzip  # $engorgio zippedName
  alias legilimens='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'  # see the hidden thoughts!
  alias occlumens='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'  # keep hidden things hidden!
  alias obliviate='history -c; history -w'  # clear bash history
  alias obscuro='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'  # lock screen
  alias tergeo='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'  # makes surfaces clean!
  alias untergeo='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'  # (this one isn't canon)
  alias expectoPatronum='nyan'  # summon your spirit animal!
fi
