#!/usr/bin/env bash

### Paths
alias paths='echo -e ${PATH//:/\\n}'

# user bin
export PATH="$PATH:$HOME/bin"

# brew
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$PATH:$HOME/.gem/bin"

# go
export PATH="$PATH:$(go env GOPATH)/bin"

# MacPorts
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

# nvm
export NVM_DIR="$HOME/.nvm"

# frameworks
export PATH="/usr/local/bin/react-native:$PATH"
export PATH="/usr/local/opt/flutter/bin:$PATH"

# android
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
