tap "bashdot/tap"
tap "bramstein/webfonttools"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "lautis/refined-github-safari"
tap "lukakerr/things"
tap "miderwong/flutter"
brew "ack"
brew "aircrack-ng"
brew "apm-bash-completion"
brew "archey"
brew "xz"
brew "python"
brew "asciinema"
brew "asciiquarium"
brew "node"
brew "ask-cli"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bash-snippets"
brew "bats"
brew "bear"
brew "bfg"
brew "binutils"
brew "gmp"
brew "p7zip"
brew "binwalk"
brew "blueutil"
brew "brew-cask-completion"
brew "calc"
brew "cask"
brew "cifer"
brew "clib"
brew "cocoapods"
brew "composer"
brew "coreutils"
brew "cowsay"
brew "dex2jar"
brew "dns2tcp"
brew "docker"
brew "dockutil"
brew "fcrackzip"
brew "fdupes"
brew "lame"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "foremost"
brew "fortune"
brew "geoip"
brew "gibo"
brew "git"
brew "git-lfs"
brew "git-standup"
brew "gnu-sed"
brew "gnupg", link: false
brew "go"
brew "googler"
brew "netpbm"
brew "graphviz"
brew "grep"
brew "hashpump"
brew "lua"
brew "howdoi"
brew "htop"
brew "httpie"
brew "hub"
brew "hydra", link: false
brew "ical-buddy"
brew "imagemagick"
brew "john"
brew "jq"
brew "knock"
brew "lolcat", link: false
brew "lynx"
brew "m-cli"
brew "mackup"
brew "mas"
brew "moreutils"
brew "multimarkdown"
brew "neofetch"
brew "netcat"
brew "nmap"
brew "nsnake"
brew "nvm"
brew "open-completion"
brew "openssh"
brew "php"
brew "pigz"
brew "pinentry-mac"
brew "pip-completion"
brew "platformio"
brew "pngcheck"
brew "pv"
brew "rbenv"
brew "react-native-cli"
brew "redis"
brew "rename"
brew "rlwrap"
brew "rtv"
brew "ruby"
brew "scrcpy"
brew "screen"
brew "shairport-sync"
brew "shellcheck"
brew "shpotify"
brew "socat"
brew "speedtest-cli"
brew "sqlmap"
brew "ssh-copy-id"
brew "starship"
brew "switchaudio-osx"
brew "tag"
brew "tcpflow"
brew "tcpreplay"
brew "tcptrace"
brew "thefuck"
brew "tldr"
brew "tree"
brew "ucspi-tcp"
brew "vbindiff"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "whois"
brew "wifi-password"
brew "woff2"
brew "xpdf"
brew "yarn"
brew "yarn-completion"
brew "yosys"
brew "youtube-dl"
brew "z"
brew "zopfli"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "bashdot/tap/bashdot"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "heroku/brew/heroku"
brew "khanhas/tap/spicetify-cli"
brew "miderwong/flutter/flutter"
cask "8bitdo-firmware-updater"
cask "aerial"
cask "amazon-music"
cask "android-platform-tools"
cask "android-studio"
cask "anki"
cask "applepi-baker"
cask "arduino"
cask "atom"
cask "background-music"
cask "barrier"
cask "beardedspice"
cask "bettertouchtool"
cask "betterzip"
cask "blackhole"
cask "boom-3d"
cask "caffeine"
cask "cakebrew"
cask "caprine"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "duet"
cask "eclipse-java"
cask "electric-sheep"
cask "emojipedia"
cask "epubquicklook"
cask "fastlane"
cask "font-fira-code"
cask "font-powerline-symbols"
cask "font-roboto"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "hazeover"
cask "hyper"
cask "iina"
cask "imageoptim"
cask "isimulator"
cask "iterm2"
cask "java"
cask "kap"
cask "keybase"
cask "keyboardcleantool"
cask "kodi"
cask "launchrocket"
cask "lyricsx"
cask "mattermost"
cask "midi-monitor"
cask "mtmr"
cask "musaicfm"
cask "noun-project"
cask "now"
cask "oni"
cask "openemu"
cask "overkill"
cask "philips-hue-sync"
cask "pine"
cask "postman"
cask "provisionql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlplayground"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "react-native-debugger"
cask "refined-github-safari"
cask "retroarch"
cask "riot"
cask "script-debugger"
cask "sketch"
cask "sketch-toolbox"
cask "skyfonts"
cask "slack"
cask "smcfancontrol"
cask "sonic-pi"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "steelseries-engine"
cask "sublime-text"
cask "suspicious-package"
cask "telegram"
cask "touch-bar-simulator"
cask "twine"
cask "ubersicht"
cask "unity"
cask "unity-hub"
cask "visual-studio-code"
cask "vnc-viewer"
cask "webpquicklook"
cask "whatsapp"
cask "workbench"
cask "wwdc"
cask "yt-music"
cask "zoomus"
mas "1Blocker", id: 1107421413
mas "1Keyboard", id: 766939888
mas "AdGuard for Safari", id: 1440147259
mas "Affinity Designer", id: 824171161
mas "Amphetamine", id: 937984704
mas "Any.do", id: 944960179
mas "Bear", id: 1091189122
mas "Cleaner-App", id: 1013897218
mas "CodeCows", id: 1176112058
mas "com.rpatechnology.mobilemouse", id: 412814284
mas "Dark Reader for Safari", id: 1438243180
mas "Disk Graph", id: 697942581
mas "Downlink", id: 1454269192
mas "Final Cut Pro", id: 424389933
mas "Gemini 2", id: 1090488118
mas "Gifski", id: 1351639930
mas "Grammarly for Safari", id: 1462114288
mas "Helium", id: 1054607607
mas "Image2icon", id: 992115977
mas "Instapaper", id: 1481302432
mas "iStudiez Pro", id: 402989379
mas "JSON Helper", id: 453114608
mas "Keynote", id: 409183694
mas "Letterpress", id: 1070543522
mas "Letters", id: 1233167730
mas "Lifeslide", id: 1472966601
mas "Localizable.strings", id: 1063953896
mas "Logic Pro X", id: 634148309
mas "Magnet", id: 441258766
mas "MainStage 3", id: 634159523
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 992076693
mas "Negative", id: 1378123825
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Outbank", id: 1094255754
mas "Pages", id: 409201541
mas "Parallels Desktop Lite", id: 1085114709
mas "PiPifier", id: 1160374471
mas "PopClip", id: 445189367
mas "Reverb", id: 1144697855
mas "Shazam", id: 897118787
mas "SiteSucker", id: 442168834
mas "Skitch", id: 425955336
mas "Spark", id: 1176895641
mas "Sparkle", id: 863015334
mas "Speedifier", id: 1212622564
mas "Speedtest", id: 1153157709
mas "Spek", id: 1465321502
mas "Super Impossible Road", id: 1465855920
mas "Telegram", id: 747648890
mas "Termius", id: 1176074088
mas "The Unarchiver", id: 425424353
mas "Tonebridge Guitar Effects", id: 1263858588
mas "Transmit", id: 1436522307
mas "Trello", id: 1278508951
mas "Turn Off the Lights for Safari", id: 1273998507
mas "TweetDeck", id: 485812721
mas "Twitter", id: 1482454543
mas "Type2Phone", id: 472717129
mas "Unsplash Wallpapers", id: 1284863847
mas "VirtualDJ", id: 1061963639
mas "VPN Plus", id: 1202726435
mas "Xcode", id: 497799835
