# frozen_string_literal: true

source "https://rubygems.org" do

gem "rails"
gem "bundler"
gem "coltrane"
gem 'jekyll'
gem 'facebook-cli'
gem 'lolcommits'
gem 'wifi-wand'
gem 'with_anybar'
gem 'github-pages', group: :jekyll_plugins
gem "jekyll-github-metadata"
gem "jekyll-octicons"
gem "jemoji"


end
